#lang racket

; Each new term in the Fibonacci sequence is generated by adding
; the previous two terms. By starting with 1 and 2, the first 10 terms will be:

; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

; By considering the terms in the Fibonacci sequence whose values do not exceed
; four million, find the sum of the even-valued terms.

(define (fib ceil)
  (let loop ([xs '()] [a 0] [b 1])
    (if (> (+ a b) ceil)
        xs
        (loop (cons (+ a b) xs) b (+ a b)))))

(define (sum xs)
  (foldl + 0 xs))

(sum (filter even? (fib (* 4 (expt 10 6)))))

; => 4613732